away_lineup = [
    {'name':'ichiro suzuki',
    'on_base': 10,
    'put_out': 0,
    'strike_out': 0,
    'ground_out': 3,
    'fly_out': 5,
    'walk': 9,
    'single': 19,
    'single_plus': 19,
    'double': 20,
    'triple': 0,
    'home_run': 21,
        },
    {'name':'alex rodriguez',
    'on_base': 10,
    'put_out': 0,
    'strike_out': 3,
    'ground_out': 4,
    'fly_out': 4,
    'walk': 11,
    'single': 15,
    'single_plus': 16,
    'double': 18,
    'triple': 0,
    'home_run': 21
        },
    {'name':'jason giambi', 
    'on_base': 11,
    'put_out': 0,
    'strike_out': 2,
    'ground_out': 0,
    'fly_out': 3,
    'walk': 12, 
    'single': 15,
    'single_plus': 0,
    'double': 18,
    'triple': 0,
    'home_run': 21
        },
    {'name':'fernando tatis',
    'on_base': 10,
    'put_out': 0,
    'strike_out': 4,
    'ground_out': 0,
    'fly_out': 6,
    'walk': 12, 
    'single': 15,
    'single_plus': 16,
    'double': 18,
    'triple': 0,
    'home_run': 21
        },
    {'name':'brian giles',
    'on_base': 10,
    'put_out': 0,
    'strike_out': 0,
    'ground_out': 3,
    'fly_out': 4,
    'walk': 11, 
    'single': 16,
    'single_plus': 0,
    'double': 18,
    'triple': 0,
    'home_run': 21,
        },
    {'name':'frank thomas',
    'on_base': 10,
    'put_out': 0,
    'strike_out': 0,
    'ground_out': 3,
    'fly_out': 6,
    'walk': 12, 
    'single': 18,
    'single_plus': 0,
    'double': 20,
    'triple': 0,
    'home_run': 21,
        },
    {'name':'david justice',
    'on_base': 10, 
    'put_out': 0,
    'strike_out': 3,
    'ground_out': 5,
    'fly_out': 6,
    'walk': 13, 
    'single': 18,
    'single_plus': 0,
    'double': 19,
    'triple': 0,
    'home_run': 21,
        },
    {'name':'jorge posada',
    'on_base': 10,
    'put_out': 5,
    'strike_out': 0,
    'ground_out': 0,
    'fly_out': 0,
    'walk': 13, 
    'single': 17,
    'single_plus': 0,
    'double': 19,
    'triple': 0,
    'home_run': 21,
        },
    {'name':'luis castillo',
    'on_base': 10,
    'put_out': 0,
    'strike_out': 2,
    'ground_out': 5,
    'fly_out': 0,
    'walk': 6, 
    'single': 13,
    'single_plus': 16,
    'double': 19,
    'triple': 10,
    'home_run': 21
        },
    ]

away_pitching_staff = [
    {'name':'curt schilling',
    'control':6,
    'innings': 8,
    'put_out': 8,
    'strike_out': 6,
    'ground_out': 12,
    'fly_out': 16,
    'walk': 17,
    'single': 20,
    'single_plus': 0,
    'double': 21,
    'home_run': 0,
        },
    {'name':'paul quantrill',
    'control': 5, 
    'innings': 1,
    'put_out': 3,
    'strike_out': 7,
    'ground_out': 15,
    'fly_out': 17,
    'walk': 0,
    'single': 20,
    'single_plus': 0,
    'double': 21,
    'home_run': 0,
        },
    {'name':'kazuhiro sasaki',
    'control': 5, 
    'innings': 1,
    'put_out': 3,
    'strike_out': 10,
    'ground_out': 14,
    'fly_out': 17,
    'walk': 19,
    'single': 20,
    'single_plus': 0,
    'double': 21,
    'home_run': 0,
        },
    {'name':'aru subu',
    'control': 5, 
    'innings': 100,
    'put_out': 3,
    'strike_out': 7,
    'ground_out': 15,
    'fly_out': 17,
    'walk': 0,
    'single': 20,
    'single_plus': 0,
    'double': 21,
    'home_run': 0,
        },
    ]