home_lineup = [
    {'name':'andruw jones',
    'on_base': 9,
    'put_out': 0,
    'strike_out': 2,
    'ground_out': 5,
    'fly_out': 6,
    'walk': 9,
    'single': 14,
    'single_plus': 15,
    'double': 17,
    'triple': 18,
    'home_run': 21,
        },
    {'name':'nomar garciaparra',
    'on_base': 10,
    'put_out': 0,
    'strike_out': 0,
    'ground_out': 3,
    'fly_out': 5,
    'walk': 8,
    'single': 15,
    'single_plus': 16,
    'double': 19,
    'triple': 0,
    'home_run': 21,
        },
    {'name':'manny ramirez', 
    'on_base': 10,
    'put_out': 0,
    'strike_out': 3,
    'ground_out': 0,
    'fly_out': 0,
    'walk': 9, 
    'single': 15,
    'single_plus': 0,
    'double': 18,
    'triple': 0,
    'home_run': 21,
        },
    {'name':'jim thome',
    'on_base': 10,
    'put_out': 0,
    'strike_out': 5,
    'ground_out': 0,
    'fly_out': 0,
    'walk': 14, 
    'single': 17,
    'single_plus': 0,
    'double': 18,
    'triple': 0,
    'home_run': 21,
        },
    {'name':'jim edmonds',
    'on_base': 10,
    'put_out': 0,
    'strike_out': 4,
    'ground_out': 0,
    'fly_out': 5,
    'walk': 12, 
    'single': 16,
    'single_plus': 0,
    'double': 17,
    'triple': 0,
    'home_run': 21
        },
    {'name':'vladimir guerrero',
    'on_base': 9,
    'put_out': 0,
    'strike_out': 4,
    'ground_out': 0,
    'fly_out': 5,
    'walk': 12, 
    'single': 16,
    'single_plus': 0,
    'double': 17,
    'triple': 0,
    'home_run': 21
        },
    {'name':'chipper jones',
    'on_base': 9, 
    'put_out': 0,
    'strike_out': 0,
    'ground_out': 3,
    'fly_out': 4,
    'walk': 10, 
    'single': 15,
    'single_plus': 16,
    'double': 18,
    'triple': 0,
    'home_run': 21,
        },
    {'name':'jason kendall',
    'on_base': 10,
    'put_out': 0,
    'strike_out': 0,
    'ground_out': 4,
    'fly_out': 5,
    'walk': 11, 
    'single': 16,
    'single_plus': 18,
    'double': 20,
    'triple': 0,
    'home_run': 21,
        },
    {'name':'pokey reese',
    'on_base': 7,
    'put_out': 0,
    'strike_out': 0,
    'ground_out': 3,
    'fly_out': 5,
    'walk': 6, 
    'single': 13,
    'single_plus': 16,
    'double': 19,
    'triple': 10,
    'home_run': 21,
        },
    ]

home_pitching_staff = [
    {'name':'greg maddux',
    'control': 6,
    'innings': 7,
    'put_out': 3,
    'strike_out': 7,
    'ground_out': 14,
    'fly_out': 0,
    'walk': 17,
    'single': 20,
    'single_plus': 0,
    'double': 21,
    'home_run': 0,
        },
    {'name':'rod beck',
    'control': 6, 
    'innings': 1,
    'put_out': 4,
    'strike_out': 8,
    'ground_out': 13,
    'fly_out': 16,
    'walk': 17,
    'single': 20,
    'single_plus': 20,
    'double': 21,
    'home_run': 0,
        },
    {'name':'ugueth urbina',
    'control': 6, 
    'innings': 1,
    'put_out': 11,
    'strike_out': 9,
    'ground_out': 13,
    'fly_out': 16,
    'walk': 18,
    'single': 21,
    'single_plus': 0,
    'double': 0,
    'home_run': 0,
        },
    {'name':'danny zela',
    'control': 6, 
    'innings': 100,
    'put_out': 4,
    'strike_out': 8,
    'ground_out': 13,
    'fly_out': 16,
    'walk': 17,
    'single': 20,
    'single_plus': 20,
    'double': 21,
    'home_run': 0,
        },
    ]